- All videos, readings, and graded assessments completed
- Gained a solid foundation in cybersecurity principles and data protection
- Learned to "think like a hacker" to better understand defense strategies
- Covered common threats such as phishing, social engineering, and ransomware
- Developed skills to implement best practices in protecting personal and organizational data
- Emphasized safe behaviors when connected to public networks
